### ISSUE TITLE
possible update to 0.11 might be helpful?

### ISSUE THREAD

**Issue by AyashiNoCeres** [robmikh/screenshot-rs#2]
Would be great if you ever found the time, to update this to the latest version of windows-rs.

Updates to window-rs are absolutely brutal and break everything. I used this project as a base for one of my own projects, but haven't managed to completely upgrade it as there are just so many breaking changes i can't solve them all.

Particularly the GetInterface method which i really just don't know how to fix for version 0.11.0
https://github.com/robmikh/screenshot-rs/blob/834542d2726ba2c892bd1ceff220b9b2809cc247/src/d3d.rs#L69

**Comment by robmikh** [comment]
Done! You can find it with commit c97d31cfcd359c77ac2c460537b7c82028165492.

It looks like functions with a signature similar to `QueryInterface` now have some syntactic sugar, which is a welcome change. You can now do this:
https://github.com/robmikh/screenshot-rs/blob/c97d31cfcd359c77ac2c460537b7c82028165492/src/d3d.rs#L63-L69

**Comment by robmikh** [comment]
Something I found useful is looking at the generated output to look at function signatures. You can find it under the `target` directory:

`screenshot-rs\target\debug\build\bindings-<some hash>\out\windows.rs`
