### ISSUE TITLE
screenshot.rs/capture.rs query

### ISSUE THREAD

**Issue by MRahilly** [robmikh/screenshot-rs#3]
Why is 'as *mut _' duplicated on line 88?

   88    &mut cloaked as *mut _ as *mut _,

**Comment by robmikh** [comment]
`cloaked` is a `u32`, but `DwmGetWindowAttribute` expects a `*mut c_void`. So first we cast to a `*mut u32` and from there cast to a `*mut c_void`. You can't make that jump directly, AFAIK.
