### ISSUE TITLE
Capturing video

### ISSUE THREAD

**Issue by qdlmcfresh** [robmikh/screenshot-rs#4]
Hi, could you maybe add an example for capturing video like here https://github.com/MicrosoftDocs/SimpleRecorder?

**Comment by robmikh** [comment]
This may be what you're looking for:

https://github.com/robmikh/displayrecorder

Although it uses Media Foundation directly instead of Windows.Media.Transcoding.

**Comment by qdlmcfresh** [comment]
thanks :)

**Comment by robmikh** [comment]
No problem! Let me know if you have any questions. Although I should warn you that I'm by no means a Media Foundation expert, my background is in the capture side of things.

I'm also on holiday until the new year, so responses may be delayed.
